services:
  app:
    image: nextjs-docker
    container_name: nextjs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev

  jenkins:
    image: jenkins/jenkins:lts-jdk17  # Use the LTS (Long Term Support) image with JDK 17
    container_name: jenkins
    build:
      context: .
      dockerfile: JenkinsDockerfile
    user: root  # Run Jenkins as root user to allow Docker-in-Docker
    ports:
      - "8080:8080"
      - "50000:50000"  # For Jenkins agents
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket for Docker-in-Docker
    privileged: true  # Allow Docker-in-Docker
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock # Ensure Jenkins can talk to Docker host
    restart: always # Restart Jenkins if it crashes

volumes:
  jenkins_home:
  app: