services:
  app:
    image: nextjs-docker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev

  jenkins:
    image: jenkins/jenkins:lts-jdk17  # Use the LTS (Long Term Support) image with JDK 17
    ports:
      - "8080:8080"
      - "50000:50000"  # For Jenkins agents
    volumes:
      - jenkins_home:/var/jenkins_home # Persist Jenkins data
    restart: always # Restart Jenkins if it crashes

volumes:
  jenkins_home:
  app: